### ISSUE TITLE
As a DEVELOPER, There needs to be an updated process to move published rules from the editor container in cosmosdb to the library published rule storage

### ISSUE THREAD

**Issue by gcampion-cdisc** [cdisc-org/conformance-rules-editor#118]
Previously the cdisc-library-conformance-rules-generator moved rules from drupal to the library published rule storage. The source of the rules need to be changed from drupal to the editor container in cosmosdb and the rules should not need to go through a transformation.

AC:
- A periodic process can run that moves published rules from the editor container in cosmosdb to the library published rule storage
- Rules are no longer transformed when going from the editor to the library.

**Comment by nhaydel** [comment]
This is done with the update in the library to pull rules from the db
