### ISSUE TITLE
Rule Editor Crashes when a rule is executed that does not Specify a Core attribute

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/conformance-rules-editor#187]
To Reproduce:
1. Select a Rule
2. Remove the Entire `Core` property and value
3. Test the rule by providing a test data file

The screen will go white. The rule editor api returns a 400 with the following message: {error: "KeyError", message: "'conditions'"}

AC
Rule Editor should not crash if a Core property is not specified. It should still be able to execute the rule.

**Comment by nickdedonder** [comment]
The screen doesn't go white but it still return the 400 failure which is fine.
