### ISSUE TITLE
As a CORE Rules Author, I want the CORE editor to switch schemas based on the current standard being authored

### ISSUE THREAD

**Issue by OGarcia11** [cdisc-org/conformance-rules-editor#51]
**Acceptance Criteria**
- When a standard is specified in the CORE yaml, the editor should switch from the base schema to the current schema being authored.

**Effort**
3

**Comment by gcampion-cdisc** [comment]
This issue may go away if CROG decides to use a universal schema.

**Comment by gcampion-cdisc** [comment]
CROG has decided to use a universal schema
