### ISSUE TITLE
Export button

### ISSUE THREAD

**Issue by OGarcia11** [cdisc-org/conformance-rules-editor#60]
**Acceptance Criteria**
Export button creates a zip file with all artifacts. For each rule:

- YAML Rule
- YAML Syntax results
- YAML Schema results
- JSON Rule
- Excel test file
- JSON test data
- Test Engine request
- Test Engine results

**Effort**

- 3

**Comment by RamilCDISC** [comment]
The downloading feature of the artifacts is functioning properly, and all the necessary files are accessible. However, I observed an issue when clicking the "Download Artifacts" button without any uploaded files or datasets. In this case, the system generates all the files and creates a zip file. Unfortunately, the Excel dataset file within the generated zip encounters an error when attempting to open it. Conversely, if datasets are uploaded and a dataset file is created, it opens without any issues. However, when the datasets section is left empty in the rule editor, the dataset file fails to open and produces an error. You can view the error in the attached screenshot. The json file for the dataset opens without any issues and is empty as it should be when no data is present.

<img width="1371" alt="60" src="https://github.com/cdisc-org/conformance-rules-editor/assets/113539111/2d3ffec1-ce51-4fdf-b96a-c9ab52c4680f">

**Comment by gerrycampion** [comment]
> The downloading feature of the artifacts is functioning properly, and all the necessary files are accessible. However, I observed an issue when clicking the "Download Artifacts" button without any uploaded files or datasets. In this case, the system generates all the files and creates a zip file. Unfortunately, the Excel dataset file within the generated zip encounters an error when attempting to open it. Conversely, if datasets are uploaded and a dataset file is created, it opens without any issues. However, when the datasets section is left empty in the rule editor, the dataset file fails to open and produces an error. You can view the error in the attached screenshot. The json file for the dataset opens without any issues and is empty as it should be when no data is present.
> 
> <img alt="60" width="1371" src="https://user-images.githubusercontent.com/113539111/243785082-2d3ffec1-ce51-4fdf-b96a-c9ab52c4680f.png">

@RamilCDISC , I've created a new issue here to address this bug.

**Comment by RamilCDISC** [comment]
Since  we will review the bug fixes in the new issue https://github.com/cdisc-org/conformance-rules-editor/issues/189, closing this issue.
